openAPI:
    info:
        title: Gravitee.io Scoring Provider API
        description: |-
            This is the OpenAPI specification for the Gravitee.io all Scoring Provider.
        version: "${project.version}"
